# Generated by Django 5.0.5 on 2024-05-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='produtos',
            name='fotos',
            field=models.ManyToManyField(to='app.foto'),
        ),
    ]
